config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :categories
  resources :layouts
  resources :products
  resources :offers
  resources :questions
  

   root 'products#index'








end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
	validates :nombre,
		presence: true,
		uniqueness: {message: "No se puede repetir las categorias"}

	default_scope -> { order("nombre") }
end

app/models/offer.rb
class Offer < ActiveRecord::Base

	belongs_to :product
	belongs_to :user

		validates :razon,
			presence: true
		validates :precio, 
			presence: true,
			inclusion: 1..9999
		validates :tarjeta,
			presence: true,
			numericality: true
		validates :codigo,
			presence: true,
			numericality: true
				

end

app/models/product.rb
class Product < ActiveRecord::Base
	
	default_scope -> { order("vencimiento") }

	def self.search(search)
		where("nombre ILIKE ? OR descripcion ILIKE ?", "%#{search}%", "%#{search}%")
	end

	validates_presence_of :nombre
	validates_presence_of :descripcion
	validates_presence_of :foto
	

	belongs_to :category
	belongs_to :user
	has_many :offers, dependent: :destroy
	has_many :questions, dependent: :destroy
end

app/models/question.rb
class Question < ActiveRecord::Base
	
	default_scope -> { order("created_at") }

	belongs_to :product
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 has_many :products
 has_many :questions
 has_many :offer

	validates :nombre,
		presence: true
	validates :apellido,
		presence: true
	validates :nacimiento,
		presence: true
	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


    before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:nombre, :apellido, :nacimiento, :email, :password) }
            devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:nombre, :apellido, :nacimiento, :email, :password, :current_password) }
        end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def show
	end

	def edit
		@cate = Category.find(params[:id])
	end

	def update
		@cate = Category.find(params[:id])
		if @cate.update_attributes(params.require(:category).permit(:nombre))
			flash[:success]= "Se modificado la categoria correctamente"
			redirect_to categories_path
		else 
			flash[:notice]= "Ocurrio un error al guardar la categoria"
			render :edit
		end
	end

	def index
		@cate = Category.all
	end

	def new
 		@cate= Category.new
	end

	def create
		@cate= Category.new(params.require(:category).permit(:nombre))
		if @cate.save
			flash[:success]= "Se creado la categoria correctamente"
			redirect_to categories_path
		else
			flash[:notice]= "Ocurrio un error al guardar la categoria"
			render :new
		end
	end


	def destroy
		categoria = Category.find(params[:id])
		categoria.destroy
		redirect_to categories_path
	end

end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

	def index
		#@offer=Offer.where(:product_id params[:id])
	end	


	def create
		@offer= Offer.new(params.require(:offer).permit(:razon, :precio, :tarjeta, :codigo, :product_id))
		@offer.client_id = current_user.id
		if @offer.save
			flash[:success]= "Se creado la oferta correctamente"
			redirect_to product_path(@offer.product_id)
		else
			flash[:danger]= "Ocurrio un error al guardar la oferta"
			redirect_to products_path
		end
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

def calculo
	@fecha= Date.today + Integer(params['cantidad_dias'])
end	

def index
	if params[:search]
		@prod=Product.search(params[:search])
	else 
		@prod = Product.all		
	end
	@prod =@prod.where("vencimiento> '#{Date.today}'")

end

def show
	@prod = Product.find(params[:id])
	@q = Question.where(product_id: @prod.id)
	if current_user
		o = Offer.where(product_id: @prod.id, client_id: current_user.id)
		@ya_oferto = o.empty?
		if @ya_oferto && (current_user.id != @prod.user_id)
			@offer = Offer.new
		end
		@question = Question.new
	end
end

def new
	@prod= Product.new
end

def create
	fecha= Date.today + Integer(params['cantidad_dias'])
	@prod= Product.new(params.require(:product).permit(:nombre, :category_id, :descripcion, :foto).merge(vencimiento: fecha))
	@prod.user_id = current_user.id
		if @prod.save
			flash[:success]= "Se creado el producto correctamente"
			redirect_to products_path
		else
			flash[:danger]= "Ocurrio un error al guardar el producto"
			render :new
		end
end


def destroy
		product = Product.find(params[:id])
		product.destroy
		redirect_to products_path
	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController


	def edit
		@q = Question.find(params[:id])
	end

	def update
		@q = Question.find(params[:id])
		if @q.update_attributes(params.require(:question).permit(:respuesta))
			flash[:success]= "Se ha enviado la respuesta correctamente"
			redirect_to product_path(@q.product_id)
		else 
			flash[:notice]= "Ocurrio un error al enviar la respuesta"
			render :edit
		end
	end

	def create
		@question= Question.new(params.require(:question).permit(:product_id, :pregunta, :respuesta))
		@question.client_id = current_user.id
		if @question.save
			flash[:success]= "Se creado la pregunta correctamente"
			redirect_to product_path(@question.product_id)
		else
			flash[:danger]= "Ocurrio un error al guardar la pregunta"
			redirect_to products_path
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
	end

	def index
		@user = User.all
	end

	def new
 		@user= User.new
	end

	def create
		@user= User.new(params.require(:user).permit(:nombre, :apellido, :nacimiento, :email, :password))
	end


	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to root
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/Index/Index.html.erb
<h2> Pagina Principal de Bestnid </h2>
<%= link_to "" %>

app/views/categories/_form.html.erb
<div class="row">
	<div class="col-md-4">
		<%= form_for @cate do |c| %>
	<div class="form-group">
		<%= c.label :nombre %>
		<%= c.text_field :nombre, required: true, class:"form-control", placeholder:"Ingrese aqui la categoría" %>
		<% if @cate.errors[:nombre].any? %>
			<p class="help-block"><%= @cate.errors[:nombre].to_s[/\w([^"]*)/] %>.</p>
		<% end %>
     </div>
	<%= c.submit 'Guardar categoria', class:"btn btn-success" %>
<%end%>	
</div>
</div>

app/views/categories/edit.html.erb
<div class="container-fluid">
<h2>Cambiar categoria</h2>

<%= render "form" %>
</div>

app/views/categories/index.html.erb
<div class="container-fluid">
<h2> Listado de Categorias </h2>

<%= link_to "Nueva Categoria", new_category_path, class: 'btn btn-primary' %>


<table class="table table-striped">
<tr>
<th>Nombre</th>
<th>Acciones</th>
</tr>

<% @cate.each do |c| %>
<tr>
	<td> <%= c.nombre %> </td>
	<td><%= link_to 'Eliminar', category_path(c), method: :delete, data: {confirm: 'Estas seguro que quieres eliminar esta categoria'}, class: 'btn btn-danger' %>
		<%= link_to 'Editar', edit_category_path(c), class: 'btn btn-primary' %> </td>
</tr>
<% end %>

</table>
</div>

app/views/categories/new.html.erb
<div class="container-fluid">
<h2> Nueva Categoria</h2>

<%= render "form" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bestnid</title>

  <%= stylesheet_link_tag    'application', media: 'all' %> 
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

</head>

<body id="body">
	<nav class="navbar navbar-default"  id="header">
  		<div class="container-fluid" > 
			<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header" id="text1">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
		</button> 
       
      	<%= link_to root_path do %>
         <%= image_tag("avatar_Bestnid.png", width: '75') %>
       <% end %>

    	</div>
		<!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav"  id="text1">
             
        <li class="dropdown" id="text1">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" 
          role="button" aria-haspopup="true" aria-expanded="false" id="text1">
          Categorias <span class="caret">
          </span></a>
          <ul class="dropdown-menu"  id="text1">
            <li><a href="#">Category 1</a></li>
            <li><a href="#">Category 2</a></li>
            <li><a href="#">Category 3</a></li>
            <li><a href="#">Category 4</a></li>
            <li><a href="#">Category 5</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>

      <%=form_tag(products_path,class:"navbar-form navbar-left",method:'get') do %>
      	<%= text_field_tag :search,params[:search], placeholder: "Ingrese aquí lo que desea buscar del producto", size:"60px", class:"form-control" %>
      
      <%= submit_tag 'Buscar',class:"btn btn-danger" %>
	 <%end%>

      <ul class="nav navbar-nav navbar-right" >
        <% if current_user %>
    Hola <%= current_user.nombre %> <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class:"btn btn-danger" %>
     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav"  id="text3">
             
        <li class="dropdown" id="text3">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" 
          role="button" aria-haspopup="true" aria-expanded="false" id="text3">
          Opciones <span class="caret">
          </span></a>
          <ul class="dropdown-menu"  id="text3">
            <li><%= link_to 'Editar cuenta', edit_user_registration_path%></li>
            <li><%= link_to "Eliminar cuenta", registration_path('user'), data: { confirm: "¿Estas seguro de que quiere eliminar su cuenta de Bestnid?" }, method: :delete %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Publicar producto', new_product_path %></li>
            <li><%= link_to 'Ver mis productos', products_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Administrar categorias', categories_path %></li>
          </ul>
        </li>
      </ul>
<% else %>
    <%= link_to 'Iniciar Sesión', new_user_session_path, class:"btn btn-success" %>
    <%= link_to 'Crear Cuenta', new_user_registration_path, class:"btn btn-primary"%>
<% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <%= value %>
    </div>

<% end %>



  <%= yield %> 

</body>

  	<p align="center">
    <a href="#" id="text1">Nosotros</a>
  	<strong>Copyright 2013-2015 </strong>| Todos los derechos reservados
  	<strong> Bestnid</strong> |La Plata| Argentina.Las fotos son a modo ilustrativo.</p>


</html>

app/views/offers/index.html.erb
<div class="container-fluid">
<h2> Elige una oferta sobre su producto </h2>

<table class="table table-striped">
<tr>
<th>Razón</th>
<th>Acciones</th>
</tr>

<% @offer.each do |o| %>
<tr>
	<td> <%= o.razon %> </td>
	<td> <%= link_to 'Elegir oferta', offer_path(o), class: 'btn btn-primary' %> </td>
</tr>
<% end %>

</table>
</div>

app/views/products/index.html.erb
<div class="container-fluid">

<h1>Listado de productos</h1>


<table class="table table-hover">
<tr>
	<th>Nombre</th>
	<th>Categoría</th>
	<th>Descripcion</th>
	<th>Fotos</th>
	<th>Fecha de vencimiento</th>
	<th>Acciones</th>
</tr>
<% @prod.each do |p| %>
	<tr>
	<td> <%= p.nombre %> </td>
	<td> <%= p.category.nombre %> </td>
	<td> <%= p.descripcion %> </td>
	<td> <%= image_tag(p.foto , width: '75')%> </td>
	<td> <%= p.vencimiento %> </td>
	<td> <%= link_to 'Ver detalle', product_path(p), class: 'btn btn-primary' %> </td>
	</tr>
	<% end %>


</table>

</div>

app/views/products/new.html.erb
<div class="container-fluid">
<h1>Subir un nuevo producto</h1>

<div class="row">
  <div class="col-md-4">

<%= form_for @prod do |f| %>
<p>
    <div class="field">
      <%= f.label :nombre %><br/>
      <%= f.text_field :nombre, autofocus: true, class:"form-control", placeholder:"Ingrese aquí el nombre" %>
    </div>
</p>

<p>
<div class="field">
<%= f.label :category_id, "Categoría" %><br />
<%= collection_select(:product, :category_id, Category.all, :id, :nombre, {})%>
</p>

<p>
    <div class="field">
      <%= f.label :descripcion %><br/>
      <%= f.text_area :descripcion, autofocus: true, class:"form-control", placeholder:"Ingrese aquí la descripcion" %>
    </div>
</p>

<p>
  <div class="field">
    <%= f.label :foto %><br />
    <%= f.text_field :foto, autofocus: true, class:"form-control", placeholder:"Ingrese aquí el link de la foto" %>
  </div>
</p>

<p>
<div class="field">
    <%= f.label "Duración del producto" %><br />
    <%= select_tag 'cantidad_dias',
     options_for_select(15..30), class:"form-control" %>
</div>
</p>

<%= f.hidden_field :fecha, :value => @fecha %>

  <div class="actions">
    <%= f.submit "Subir producto", class:"btn btn-primary" %>
  </div>
<%end%>

</div>
</div>
</div>

app/views/products/show.html.erb
<div class="container-fluid">
<h2> <%= @prod.nombre %> </h2>
<h4> <%= @prod.category.nombre %> </h4>
<div class="row">

	<div class="col-md-8"><%= @prod.descripcion %></div>

	<div class="col-md-4"><%= image_tag(@prod.foto, width: '250')%></div>

</div>

<% if current_user && (@prod.user_id == current_user.id) %>
  <% if @prod.vencimiento <= Date.today %>
  <%= link_to 'Ver ofertas', offers_path , class: 'btn btn-primary' %>
  <% end %>
  <%= link_to 'Eliminar', product_path(@prod), method: :delete, data: {confirm: 'Estas seguro que quieres eliminar este producto'}, class: 'btn btn-danger' %>
  <%= link_to 'Editar', edit_product_path(@prod), class: 'btn btn-success' %>

  <table class="table table-hover">
  <tr>
    <th>Pregunta</th>
    <th>Respuesta</th>
    <th>Responder</th>
  </tr>
  <% @q.each do |p| %>
  <tr>
    <td> <%= p.pregunta %> </td>
    <td> <%= p.respuesta %> </td>
    <% if p.respuesta.nil? %>
    <td> <%= link_to 'Responder', edit_question_path(p), class: 'btn btn-primary' %></td>
    <% end %>
  </tr>
  <% end %>

 </table>
<% end %> 

<% if !(current_user && (@prod.user_id == current_user.id)) %>

  <table class="table table-hover">
  <tr>
    <th>Pregunta</th>
    <th>Respuesta</th>
  </tr>
  <% @q.each do |p| %>
    <tr>
      <td> <%= p.pregunta %> </td>
      <td> <%= p.respuesta %> </td>
    </tr>
  <% end %>
  </table>



  <div class="row">
  <div class="col-md-4">

  <% if current_user %>
  <h4>Preguntar sobre el producto</h4>
  <%= form_for @question do |f| %>
  <p>
    <%= f.label :pregunta %><br>
    <%= f.text_area :pregunta, autofocus: true, class:"form-control", placeholder:"Ingrese aquí la pregunta que desea preguntarle al vendedor sobre el producto" %>
  </p>
  <%= f.hidden_field :product_id, :value => @prod.id %>
  <p>
    <%= f.submit "Enviar la pregunta", class:"btn btn-primary"  %>
  </p>
<% end %> 
<% end %>
</div>

 <% if @ya_oferto %>
  <div class="col-md-4">

  <h4>Cree una oferta</h4>
  <%= form_for @offer do |f| %>
  <p>
    <%= f.label :razon %><br>
    <%= f.text_area :razon, autofocus: true, class:"form-control", placeholder:"Ingrese aquí la razón por la cual desea comprar el producto" %>
  </p>
  <p>
    <%= f.label :precio %><br>
    <%= f.number_field :precio, autofocus: true, class:"form-control", placeholder:"Ingrese aquí el precio" %>
  </p>
  <p>
    <%= f.label :tarjeta %><br>
    <%= f.text_field :tarjeta, autofocus: true, class:"form-control", placeholder:"Ingrese aquí el número de tarjeta de crédito" %>
  </p>
  <p>
    <%= f.label :codigo %><br>
    <%= f.password_field :codigo, autofocus: true, class:"form-control", placeholder:"Ingrese aquí el codigo de su tarjeta" %>
  </p>
  <%= f.hidden_field :product_id, :value => @prod.id %>
  <p>
    <%= f.submit "Crear oferta", class:"btn btn-success"  %>
  </p>
  <% end %>

  </div>
  <% end %>
  </div>

 

<% end %>

</div>

app/views/questions/edit.html.erb
<div class="container-fluid">

	<h3>Responder la pregunta</h3>

	<div class="row">
		<div class="col-md-4">
			<p>Pregunta</p> </br>
			<p> <%= @q.pregunta %> </p>
		</div>
		<div class="col-md-4">
			<%= form_for @q do |c| %>
				<div class="form-group">
					<%= c.label :respuesta %>
					<%= c.text_area :respuesta, class:"form-control", placeholder:"Ingrese aqui su respuesta" %>
     			</div>
		<%= c.submit 'Enviar respuesta', class:"btn btn-success" %>
		<%end%>	
	</div>
</div>
</div>